#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..  

echo "› brew bundle"
brew bundle --verbose

# find the installers and run them iteratively
find . -name install.sh | while IFS= read -r installer ; do sh "$installer" ; done
