#!/usr/bin/env bash
#
# Run all dotfiles installers.

set -e

cd "$(dirname "$0")"/..  

echo "› brew bundle"
brew bundle --verbose

# find the installers and run them iteratively
find . -maxdepth 2 -name .git -prune -o -name install.sh -type f -print | sort | while IFS= read -r installer; do
  echo "› $installer"
  "$installer"
done
